from django.urls import path


from vault.views import (
  VaultListView,
  VaultRowsListView,
  VaultDetailView,
  vault_detail_partial,
  VaultCreateView,
  VaultUpdateView,
  delete_vault,
  delete_multiple_vault,
  VaultDeleteView,
  PasswordEntryListView, 
  PasswordEntryRowsListView,  
  PasswordEntryDetailView, 
  password_entry_detail_partial,
  PasswordEntryCreateView,
  PasswordEntryUpdateView,
  delete_password_entry,
  PasswordHistoryListView,
  PasswordHistoryDetailView,
  PasswordHistoryDeleteView,
  PasswordHistorySetView,
  ReuseMostRecentOldPasswordView,
  RemovePasswordEntryFromVaultView,
  remove_password_entry_from_vault,
  MovePasswordEntryToTrashView,
  move_password_entry_to_trash,
  move_multiple_password_entry_to_trash,
  TrashedPasswordEntryListView,
  TrashedPasswordEntryRowsView,
  restore_password_entry,
)


app_name = 'vault'

urlpatterns = [
  path('', VaultListView.as_view(), name='vault_list'),
  path('rows/', VaultRowsListView.as_view(), name='vault_list_rows'),
  path('<int:pk>/', VaultDetailView.as_view(), name='vault_detail'),
  path('partial/<int:pk>/', vault_detail_partial, name='vault_detail_partial'),
  path('create/', VaultCreateView.as_view(), name='vault_create'),
  path('update/<int:pk>/', VaultUpdateView.as_view(), name='vault_update'),
  # path('delete/<int:pk>/', VaultDeleteView.as_view(), name='vault_delete'),
  path('delete/<int:pk>/', delete_vault, name='vault_delete'),
  path('delete-multiple/', delete_multiple_vault, name='vault_delete_multiple'),
  path('passwords/<int:pk>/remove-from-vault', remove_password_entry_from_vault, name='vault_remove_password'),
  path('passwords/', PasswordEntryListView.as_view(), name='password_list'),
  path('passwords/rows', PasswordEntryRowsListView.as_view(), name='password_list_rows'),
  path('passwords/<int:pk>/', PasswordEntryDetailView.as_view(), name='password_detail'),
  path('passwords/partial/<int:pk>/', password_entry_detail_partial, name='password_detail_partial'),
  path('passwords/create/', PasswordEntryCreateView.as_view(), name='password_create'),
  path('passwords/<int:pk>/update/', PasswordEntryUpdateView.as_view(), name='password_update'),
  path('passwords/<int:pk>/delete/', delete_password_entry, name='password_delete'),
  # path('passwords/<int:pk>/remove/', RemovePasswordEntryFromVaultView.as_view(), name='password_remove_from_vault'),
  path('passwords/<int:pk>/move/', move_password_entry_to_trash, name='password_move_to_trash'),
  # path('passwords/<int:pk>/move/', MovePasswordEntryToTrashView.as_view(), name='password_move_to_trash'),
  path('passwords/move/', move_multiple_password_entry_to_trash, name='password_move_to_trash_nultiple'),
  path('passwords/<int:pk>/history/', PasswordHistoryListView.as_view(), name='password_history_list'),
  path('passwords/history/<int:pk>/', PasswordHistoryDetailView.as_view(), name='password_history_detail'),
  path('passwords/history/<int:pk>/delete/', PasswordHistoryDeleteView.as_view(), name='password_history_delete'),
  path('passwords/history/<int:pk>/set/', PasswordHistorySetView.as_view(), name='password_history_set_password'),
  path('passwords/<int:pk>/history/reuse/', ReuseMostRecentOldPasswordView.as_view(), name='password_history_reuse_most_recent_old'),
  path('trash/', TrashedPasswordEntryListView.as_view(), name='trashed_password_entries'),
  path('trash/rows', TrashedPasswordEntryRowsView.as_view(), name='trashed_password_entry_rows'),
  path('trash/restore/<int:pk>/', restore_password_entry, name='restore_password_entry'),
]
