# Generated by Django 5.0.3 on 2024-08-13 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_vault_passwordentry_vault'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordentry',
            old_name='url',
            new_name='website_url',
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='website_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='vault',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_entries', to='vault.vault'),
        ),
    ]
