# Generated by Django 5.0.3 on 2024-08-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_rename_url_passwordentry_website_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
