# Generated by Django 5.0.3 on 2024-08-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_vault_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
