# Generated by Django 5.0.3 on 2024-08-16 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.passwordentry')),
            ],
        ),
    ]
