# Generated by Django 5.0.3 on 2024-08-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_remove_passwordentry_website_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordhistory',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
