# Generated by Django 5.0.3 on 2024-08-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_passwordhistory_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
