# Generated by Django 5.0.3 on 2024-08-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_alter_passwordentry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
