# Generated by Django 5.0.3 on 2024-08-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_alter_website_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordhistory',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
