# Generated by Django 5.0.3 on 2024-08-17 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0012_passwordhistory_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordhistory',
            name='password_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vault.passwordentry'),
        ),
    ]
