# Generated by Django 5.0.3 on 2024-08-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0013_alter_passwordhistory_password_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='last_used',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
