# Generated by Django 5.0.3 on 2024-08-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0014_passwordentry_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
