# Generated by Django 5.0.3 on 2024-08-22 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0021_alter_vault_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='password_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='vault.passwordentry'),
        ),
    ]
