# Generated by Django 5.0.3 on 2024-08-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0022_alter_website_password_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_entries', to='vault.vault'),
        ),
    ]
