# Generated by Django 5.0.3 on 2024-08-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0023_alter_passwordentry_vault'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=15, null=True),
        ),
    ]
